apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django_ecommerce-api/ecommerce:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: django-storage
              mountPath: /app
      volumes:
        - name: django-storage
          emptyDir: {}
