apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          env:
            - name: POSTGRES_DB
              value: e-commerce-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: qwerty1234
            - name: PGDATA
              value: /data/postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /data/postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc